import '@prestashopcorp/puik-components/base/style'
import '@prestashopcorp/puik-theme/src/sidebar-group-item.scss'
import '@prestashopcorp/puik-theme/src/accordion.scss'
import '@prestashopcorp/puik-theme/src/button.scss'
import '@prestashopcorp/puik-theme/src/icon.scss'
