import '@prestashopcorp/puik-components/base/style/css';
import '@prestashopcorp/puik-theme/puik-select.css';
import '@prestashopcorp/puik-theme/puik-group-options.css';
import '@prestashopcorp/puik-theme/puik-option.css';
import '@prestashopcorp/puik-theme/puik-checkbox.css';
import '@prestashopcorp/puik-theme/puik-chip.css';
import '@prestashopcorp/puik-theme/puik-input.css';
import '@prestashopcorp/puik-theme/puik-icon.css';
import '@prestashopcorp/puik-theme/puik-label.css';
