 
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PuikAccordionGroup: typeof import('@prestashopcorp/puik-components')['PuikAccordionGroup']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
