import '@prestashopcorp/puik-components/base/style/css'
import '@prestashopcorp/puik-theme/puik-modal.css'
import '@prestashopcorp/puik-theme/puik-button.css'
import '@prestashopcorp/puik-theme/puik-icon.css'
import '@prestashopcorp/puik-theme/puik-tooltip.css'
