import '@prestashopcorp/puik-components/base/style'
import '@prestashopcorp/puik-theme/src/modal.scss'
import '@prestashopcorp/puik-theme/src/button.scss'
import '@prestashopcorp/puik-theme/src/icon.scss'
import '@prestashopcorp/puik-theme/src/tooltip.scss'
