import '@prestashopcorp/puik-components/base/style'
import '@prestashopcorp/puik-theme/src/puik-modal.scss'
import '@prestashopcorp/puik-theme/src/puik-button.scss'
import '@prestashopcorp/puik-theme/src/puik-icon.scss'
import '@prestashopcorp/puik-theme/src/puik-tooltip.scss'
