// GlobalComponents for Volar
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PuikNotificationBar: (typeof import('@prestashopcorp/puik-components'))['PuikNotificationBar']
    PuikTag: (typeof import('@prestashopcorp/puik-components'))['PuikTag']
    PuikTabNavigationGroupPanels: (typeof import('@prestashopcorp/puik-components'))['PuikTabNavigationGroupPanels']
    PuikTabNavigationTitle: (typeof import('@prestashopcorp/puik-components'))['PuikTabNavigationTitle']
    PuikTabNavigationGroupTitles: (typeof import('@prestashopcorp/puik-components'))['PuikTabNavigationGroupTitles']
    PuikTabNavigation: (typeof import('@prestashopcorp/puik-components'))['PuikTabNavigation']
    PuikProgressStepper: (typeof import('@prestashopcorp/puik-components'))['PuikProgressStepper']
    PuikProgressStepperStep: (typeof import('@prestashopcorp/puik-components'))['PuikProgressStepperStep']
    PuikTable: (typeof import('@prestashopcorp/puik-components'))['PuikTable']
    PuikSpinnerLoader: (typeof import('@prestashopcorp/puik-components'))['PuikSpinnerLoader']
    PuikSidebar: (typeof import('@prestashopcorp/puik-components'))['PuikSidebar']
    PuikSidebarGroupItem: (typeof import('@prestashopcorp/puik-components'))['PuikSidebarGroupItem']
    PuikSidebarItem: (typeof import('@prestashopcorp/puik-components'))['PuikSidebarItem']
    PuikSidebarTitle: (typeof import('@prestashopcorp/puik-components'))['PuikSidebarTitle']
    PuikSkeletonLoader: (typeof import('@prestashopcorp/puik-components'))['PuikSkeletonLoader']
    PuikSkeletonLoaderGroup: (typeof import('@prestashopcorp/puik-components'))['PuikSkeletonLoaderGroup']
    PuikPagination: (typeof import('@prestashopcorp/puik-components'))['PuikPagination']
    PuikTextarea: (typeof import('@prestashopcorp/puik-components'))['PuikTextarea']
    PuikBreadcrumb: (typeof import('@prestashopcorp/puik-components'))['PuikBreadcrumb']
    PuikAccordionGroup: (typeof import('@prestashopcorp/puik-components'))['PuikAccordionGroup']
    PuikAccordion: (typeof import('@prestashopcorp/puik-components'))['PuikAccordion']
    PuikBadge: (typeof import('@prestashopcorp/puik-components'))['PuikBadge']
    PuikModal: (typeof import('@prestashopcorp/puik-components'))['PuikModal']
    PuikButtonGroup: (typeof import('@prestashopcorp/puik-components'))['PuikButtonGroup']
    PuikMenu: (typeof import('@prestashopcorp/puik-components'))['PuikMenu']
    PuikMenuItem: (typeof import('@prestashopcorp/puik-components'))['PuikMenuItem']
    PuikMenuItemSeparator: (typeof import('@prestashopcorp/puik-components'))['PuikMenuItemSeparator']
    PuikMenuItemTitle: (typeof import('@prestashopcorp/puik-components'))['PuikMenuItemTitle']
    PuikProgressBar: (typeof import('@prestashopcorp/puik-components'))['PuikProgressBar']
    PuikIcon: (typeof import('@prestashopcorp/puik-components'))['PuikIcon']
    PuikOption: (typeof import('@prestashopcorp/puik-components'))['PuikOption']
    PuikSelect: (typeof import('@prestashopcorp/puik-components'))['PuikSelect']
    PuikLink: (typeof import('@prestashopcorp/puik-components'))['PuikLink']
    PuikCard: (typeof import('@prestashopcorp/puik-components'))['PuikCard']
    PuikCheckbox: (typeof import('@prestashopcorp/puik-components'))['PuikCheckbox']
    PuikLabel: (typeof import('@prestashopcorp/puik-components'))['PuikLabel']
    PuikRadio: (typeof import('@prestashopcorp/puik-components'))['PuikRadio']
    PuikInput: (typeof import('@prestashopcorp/puik-components'))['PuikInput']
    PuikAlert: (typeof import('@prestashopcorp/puik-components'))['PuikAlert']
    PuikTooltip: (typeof import('@prestashopcorp/puik-components'))['PuikTooltip']
    PuikSwitch: (typeof import('@prestashopcorp/puik-components'))['PuikSwitch']
    PuikButton: (typeof import('@prestashopcorp/puik-components'))['PuikButton']
    PuikConfigProvider: (typeof import('@prestashopcorp/puik-components'))['PuikConfigProvider']
    PuikSnackbar: (typeof import('@prestashopcorp/puik-components'))['PuikSnackbar']
    PuikSnackbarProvider: typeof import('@prestashopcorp/puik-components')['PuikSnackbarProvider']
    PuikCheckbox: (typeof import('@prestashopcorp/puik-components'))['PuikCheckbox']
    PuikLabel: (typeof import('@prestashopcorp/puik-components'))['PuikLabel']
    PuikInput: (typeof import('@prestashopcorp/puik-components'))['PuikInput']
    PuikAlert: (typeof import('@prestashopcorp/puik-components'))['PuikAlert']
    PuikTooltip: (typeof import('@prestashopcorp/puik-components'))['PuikTooltip']
    PuikSwitch: (typeof import('@prestashopcorp/puik-components'))['PuikSwitch']
    PuikButton: (typeof import('@prestashopcorp/puik-components'))['PuikButton']
    PuikConfigProvider: (typeof import('@prestashopcorp/puik-components'))['PuikConfigProvider']
  }
}

export {};
