 
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PuikAlert: typeof import('@prestashopcorp/puik-components')['PuikAlert']
    PuikAvatar: typeof import('@prestashopcorp/puik-components')['PuikAvatar']
    PuikBadge: typeof import('@prestashopcorp/puik-components')['PuikBadge']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikInput: typeof import('@prestashopcorp/puik-components')['PuikInput']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    PuikTextarea: typeof import('@prestashopcorp/puik-components')['PuikTextarea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
