name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-github-packages:
    name: Publish on registry
    runs-on: ubuntu-latest
    if: success() && !contains(github.ref, 'beta')

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Get tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Install dependencies 👨🏻‍💻
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Publish
        run: pnpm -r --filter './packages/**' publish --no-git-checks --access public
